### ISSUE TITLE
0x0AC5 is not rendering correctly

### ISSUE THREAD

**Issue by nlci-dev** [nlci/gujr-font-gir#2]
The font doesn't render the 0x0AC5 correctly.
![image](https://github.com/nlci/gujr-font-gir/assets/12891019/47bddb52-adc9-44dc-b905-df7e616e5247)

**Comment by devosb** [comment]
The character U+0AC5 GUJARATI VOWEL SIGN CANDRA E is not in the font, so no surprise that it is not rendering correctly.
